server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /auth/ {
    proxy_pass http://api-gateway:9000;
  }

  location /jobs/ {
    proxy_pass http://api-gateway:9000;
  }

  location /brokers/ {
    proxy_pass http://api-gateway:9000;
  }

  location /matches/ {
    proxy_pass http://api-gateway:9000;
  }

  location /notifications/ {
    proxy_pass http://api-gateway:9000;
  }
}
