apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: matching-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/lanka_microjob
            - name: SPRING_DATASOURCE_USERNAME
              value: lanka
            - name: SPRING_DATASOURCE_PASSWORD
              value: lanka
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
spec:
  selector:
    app: matching-service
  ports:
    - port: 8083
      targetPort: 8083
