spring.application.name=user-service
server.port=9001
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lanka_microjob}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lanka}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lanka}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
jwt.secret=lanka_microjob_jwt_secret_key_2026_very_long
jwt.expiration=86400000
