pipeline {

    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/matheehesh/SOC-testing.git'
            }
        }


        stage('Build Docker Image') {
            steps {
                bat 'docker build -f broker-service/dockerfile -t matheehesh02/microjobs broker-service'
            }
        }


        stage('Login to Docker Hub') {
            steps {
                withCredentials([
                    string(credentialsId: 'matheesha', variable: 'DOCKER_PASSWORD')
                ]) {
                    bat 'docker login -u matheehesh02 -p %DOCKER_PASSWORD%'
                }
            }
        }


        stage('Push Docker Image') {
            steps {
                bat 'docker push matheehesh02/microjobs'
            }
        }

    }


    post {

        always {
            bat 'docker logout'
        }

    }


}